name: Setup
on: push

jobs:
  setup:
    if: (github.event.commits[0].message == 'Initial commit') && (github.run_number == 1)
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
  
    - name: Copy Repository Contents
      uses: actions/checkout@v2
    - name: modify files
      run: |
        import re, os
        from pathlib import Path
        PR_template = Path('setup/PR.md')
        readme_template_path = Path('setup/README.md')
        nwo = os.getenv('GITHUB_REPOSITORY')
        username, repo_name = nwo.split('/')
        # replace content of README with template
        readme = readme_template_path.read_text().replace('{_username_}', username).replace('{_repo_name_}', repo_name)
        readme_template_path.write_text(readme)
        PR = PR_template.read_text().replace('{_username_}', username).replace('{_repo_name_}', repo_name)
        PR_template.write_text(PR)
      shell: python

    - name: commit changes
      run: |
        git config --global user.email "${GH_EMAIL}"
        git config --global user.name "${GH_USERNAME}"
        git checkout -B resume-automated-setup
        git rm .github/FUNDING.yml
        git rm .github/workflows/setup.yaml
        rm README.md
        mv setup/README.md README.md
        git add -A
        git commit -m'setup repo'
        git push -f --set-upstream origin resume-automated-setup
      env: 
        GH_EMAIL: ${{ github.event.commits[0].author.email }}
        GH_USERNAME: ${{ github.event.commits[0].author.username }}

    - name: Open a PR
      uses: actions/github-script@0.5.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          var fs = require('fs');
          var contents = fs.readFileSync('setup/PR.md', 'utf8');
          github.pulls.create({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        title: 'Initial Setup',
                        head: 'resume-automated-setup',
                        base: 'main',
                        body: `${contents}`
                        })